server:
  port: 8080
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  dataBase: nearTest
  username: root
  password: '001228'
  charset: utf8
  parseTime: True
  loc: Local
email:
  email: '858689519@qq.com'
  password: 

